### ISSUE TITLE
HERE No longer issuing App Codes

### ISSUE THREAD

**Issue by clibassi** [simonheb/geocodehere#1]
Hi there - 

I've been trying to use geocodehere - it seems like a great tool. But I see that the syntax requires an app code and an app id, but when I registered, I only received an app id and an API key, and some googling turns up that it seems like HERE has deprecated app codes except for a few mobile application uses. Is there any way to still use the command?

**Comment by simonheb** [comment]
Hi,

I haven't used geocodehere in 2 years.  But just now I signed up again for the "Freemium" on here: https://developer.here.com/pricing, got an appid and an appcode ran the code from the geocodehere helpfile without any problems. I think sometimes they call the "app code" "app key" could that be a simple confusion?

Here's what I see 
![grafik](https://user-images.githubusercontent.com/4234597/73737656-54d75300-4743-11ea-9c5f-a7fca0a8f113.png)

**Comment by clibassi** [comment]
Really appreciate your quick reply. My dashboard looks different - I think maybe because of when we registered our accounts. I am missing the JS Rest portion. Here's what mine looks like: 
 
![app_key](https://user-images.githubusercontent.com/10570262/73763233-29eb0000-473f-11ea-977d-86e5f35c397d.PNG)

![app_key2](https://user-images.githubusercontent.com/10570262/73763279-340cfe80-473f-11ea-8cf6-1a6cf4f63f51.PNG)


When I put in the API key in the place of the app code and run both my own code and the sample code from the help file I get a server connect error that seems to be about the credentials: 

![app_key4](https://user-images.githubusercontent.com/10570262/73763554-8fd78780-473f-11ea-90fa-3a4627f0d47c.PNG)

![app_key5](https://user-images.githubusercontent.com/10570262/73763561-936b0e80-473f-11ea-8c2f-79832f2634ab.PNG)

**Comment by simonheb** [comment]
Yep. Sorry, I overlooked that.

I fixed this and updated the code on github. Try downloading the new ado-file and run it with specifying your appkey(...) as specified in the new helpfile. Let me know if there's anythin still not working.

**Comment by clibassi** [comment]
This is perfect and working super well - thank you so much!
